apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/[YOUR_PROJECT_ID]/cloud-app
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb+srv://<username>:<password>@<cluster-url>/cloudApp?retryWrites=true&w=majority"
