apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: cloud-app
        image: cloud-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://mongo:27017/cloudApp"
